param(
    [string]$TextBaseUrl,
    [string]$TextApiKey,
    [string]$TextModel,
    [string]$ImageBaseUrl,
    [string]$ImageApiKey,
    [string]$ImageModel = "gpt-image-2",
    [string]$ImageSize = "1024x1024",
    [string]$EnvFile,
    [switch]$SkipText,
    [switch]$SkipImage,
    [switch]$NonInteractive
)

$ErrorActionPreference = "Stop"
$Root = Split-Path -Parent $PSScriptRoot
$EnvPath = if ([string]::IsNullOrWhiteSpace($EnvFile)) { Join-Path $Root ".env" } else { [System.IO.Path]::GetFullPath($EnvFile) }
$ImageProviderSignupUrl = "https://downstream.jbbtoken.cn/i/BuFB"

function Read-Required([string]$Label, [string]$Current, [string]$Default = "") {
    if (-not [string]::IsNullOrWhiteSpace($Current)) { return $Current }
    if ($NonInteractive) { return $Default }
    $suffix = if ($Default) { " [$Default]" } else { "" }
    $value = Read-Host "$Label$suffix"
    if ([string]::IsNullOrWhiteSpace($value)) { return $Default }
    return $value.Trim()
}

function Read-Secret([string]$Label, [string]$Current, [string]$Default = "") {
    if (-not [string]::IsNullOrWhiteSpace($Current)) { return $Current }
    if ($NonInteractive) { return $Default }
    $secureValue = Read-Host $Label -AsSecureString
    $pointer = [Runtime.InteropServices.Marshal]::SecureStringToBSTR($secureValue)
    try {
        $value = [Runtime.InteropServices.Marshal]::PtrToStringBSTR($pointer)
    } finally {
        [Runtime.InteropServices.Marshal]::ZeroFreeBSTR($pointer)
    }
    if ([string]::IsNullOrWhiteSpace($value)) { return $Default }
    return $value.Trim()
}

if (-not $SkipText) {
    $TextBaseUrl = Read-Required "文本 API Base URL" $TextBaseUrl "https://api.openai.com/v1"
    $TextModel = Read-Required "文本模型名称" $TextModel "gpt-4.1-mini"
    $TextApiKey = Read-Secret "文本 API Key（输入内容不会显示）" $TextApiKey
    if ([string]::IsNullOrWhiteSpace($TextApiKey)) {
        throw "缺少文本 API Key。通俗解释稿建议配置文本模型；不需要时请显式使用 -SkipText。"
    }
}

if (-not $SkipImage) {
    if (-not $NonInteractive) {
        Write-Host "推荐生图 API 注册入口：$ImageProviderSignupUrl"
        Write-Host "注册或登录后，请先充值、创建 API Key，并从控制台复制 API Base URL 和模型名。"
        Write-Host "邀请链接不能作为 API Base URL。项目作者可能通过该推广链接获得收益。"
        $enableImage = Read-Host "是否配置生图 API？输入 Y 配置，直接回车跳过"
        if ($enableImage -notmatch '^[Yy]$') { $SkipImage = $true }
    }
    if (-not $SkipImage) {
        $defaultImageBaseUrl = if (-not [string]::IsNullOrWhiteSpace($TextBaseUrl)) { $TextBaseUrl } else { "https://api.openai.com/v1" }
        $ImageBaseUrl = Read-Required "生图 API Base URL" $ImageBaseUrl $defaultImageBaseUrl
        $ImageModel = Read-Required "生图模型名称" $ImageModel "gpt-image-2"
        $ImageApiKey = Read-Secret "生图 API Key（输入内容不会显示）" $ImageApiKey $TextApiKey
        if ([string]::IsNullOrWhiteSpace($ImageApiKey)) { throw "缺少生图 API Key，或使用 -SkipImage 跳过配图。" }
    }
}

$lines = @("# Generated by scripts/configure.ps1")
if (-not $SkipText) {
    $lines += "TEXT_API_BASE_URL=$TextBaseUrl"
    $lines += "TEXT_API_KEY=$TextApiKey"
    $lines += "TEXT_MODEL=$TextModel"
}
if (-not $SkipImage) {
    $lines += "IMAGE_API_BASE_URL=$ImageBaseUrl"
    $lines += "IMAGE_API_KEY=$ImageApiKey"
    $lines += "IMAGE_MODEL=$ImageModel"
    $lines += "IMAGE_SIZE=$ImageSize"
    $lines += "IMAGE_RESPONSE_FORMAT=b64_json"
    $lines += "IMAGE_REQUEST_TIMEOUT_MS=360000"
}
if (Test-Path -LiteralPath $EnvPath) {
    Copy-Item -LiteralPath $EnvPath -Destination "$EnvPath.backup" -Force
}
[System.IO.File]::WriteAllLines($EnvPath, $lines, [System.Text.UTF8Encoding]::new($false))
Write-Output "CONFIG_STATUS=saved"
Write-Output "TEXT_CONFIGURED=$(-not $SkipText)"
Write-Output "IMAGE_CONFIGURED=$(-not $SkipImage)"
Write-Output "ENV_FILE=$EnvPath"
Write-Output "密钥已写入被 Git 忽略的 .env，终端不会显示密钥内容。"
